<<<<<<< HEAD
db.url=jdbc:mysql://localhost:3306/supplychain_db
db.username=root
db.password=""
db.driver=com.mysql.jdbc.Driver
=======
db.url=jdbc:mariadb://serverless-europe-west2.sysp0000.db2.skysql.com:4042/supply_chain_db?sslMode=verify-ca&serverSslCert=file:certs/globalsignrootca.pem
db.username=dbpgf23895095
db.password=4Fxf|qi2u0OFf!Bqk2sCzh2O
db.driver=org.mariadb.jdbc.Driver
>>>>>>> branch 'master' of https://github.com/hari-w8/SupplyChainOptimizationSystem
